### ISSUE TITLE
Please update to jsdiff 3.0.0

### ISSUE THREAD

**Issue by Ornedan** [webjars/diff#2]

**Comment by jamesward** [comment]
I noticed that they no longer provide compiled artifacts anymore: https://github.com/kpdecker/jsdiff

Is that ok?  Have you tried to create a NPM or Bower WebJar for this?

**Comment by Ornedan** [comment]
It seems to be possible to build a classic Webjar by adding a few steps to the ant-exec:
```npm install
grunt
yo release```
